sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t libtooling - < api-utils-common/Docker/Travis.Dockerfile
  - >
    docker run
    --name libtooling_build
    -v "${TRAVIS_BUILD_DIR}:/root/clang-llvm/llvm/tools/clang/tools/extra/check-cpp-api"
    libtooling
    /root/clang-llvm/llvm/tools/clang/tools/extra/check-cpp-api/api-utils-common/Docker/docker-test.sh
    check-cpp-api
